name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRE_PASS }}
          POSTGRES_DB: ${{ secrets.POSTGRE_DB }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install dependencies
      run: mvn install

    - name: Run unit tests
      env:
        DB_URL:  ${{ secrets.POSTGRE_LINK }}
        DB_USERNAME: ${{ secrets.POSTGRE_USER }}
        DB_PASSWORD: ${{ secrets.POSTGRE_PASS }}
      run: mvn test

    - name: Generate code coverage report
      run: mvn jacoco:report
      env:
        MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

    - name: Upload coverage to GitHub
      run: echo "${{ steps.test.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

